import { ImagePlus, Loader2, Upload, X } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { uploadCompanyLogo } from '../../services/jobs'
import { emptyJobForm, type ApplicationMethod, type Job, type JobFormValues, type WorkMode, type WorkType } from '../../types/job'
import { useToast } from '../ui/toast'

export function JobFormDrawer({ open, job, saving, onClose, onSave }: { open: boolean; job: Job | null; saving: boolean; onClose: () => void; onSave: (values: JobFormValues) => Promise<void> }) {
  const [values, setValues] = useState<JobFormValues>(emptyJobForm)
  const [requirements, setRequirements] = useState('')
  const [responsibilities, setResponsibilities] = useState('')
  const [uploading, setUploading] = useState(false)
  const { toast } = useToast()
  useEffect(() => { if (open) { const source = job ? stripJob(job) : emptyJobForm; setValues(source); setRequirements(source.requirements.join('\n')); setResponsibilities(source.responsibilities.join('\n')) } }, [open, job])
  useEffect(() => { if (!open) return; const overflow = document.body.style.overflow; document.body.style.overflow = 'hidden'; const listener = (event: KeyboardEvent) => { if (event.key === 'Escape' && !saving) onClose() }; window.addEventListener('keydown', listener); return () => { document.body.style.overflow = overflow; window.removeEventListener('keydown', listener) } }, [open, onClose, saving])
  if (!open) return null
  const set = <K extends keyof JobFormValues>(key: K, value: JobFormValues[K]) => setValues((current) => ({ ...current, [key]: value }))
  const submit = async (event: FormEvent) => { event.preventDefault(); await onSave({ ...values, requirements: splitLines(requirements), responsibilities: splitLines(responsibilities) }) }
  const upload = async (file?: File) => { if (!file) return; if (file.size > 2_000_000) { toast('Ukuran logo maksimal 2 MB.', 'error'); return } setUploading(true); try { set('company_logo_url', await uploadCompanyLogo(file)); toast('Logo perusahaan berhasil diunggah.') } catch (cause) { toast(cause instanceof Error ? cause.message : 'Logo gagal diunggah.', 'error') } finally { setUploading(false) } }
  return (
    <div className="fixed inset-0 z-[60]" role="dialog" aria-modal="true" aria-labelledby="job-form-title"><button className="absolute inset-0 bg-slate-950/40 backdrop-blur-[2px]" onClick={onClose} aria-label="Tutup formulir" /><section className="animate-slide-in absolute inset-y-0 right-0 flex w-full max-w-3xl flex-col bg-[#f8faf9] shadow-2xl sm:inset-y-3 sm:right-3 sm:rounded-3xl">
      <header className="flex items-center justify-between border-b border-slate-200 bg-white px-5 py-4 sm:rounded-t-3xl sm:px-7"><div><p className="text-[10px] font-extrabold uppercase tracking-wider text-brand-700">Manajemen Lowongan</p><h2 id="job-form-title" className="mt-1 text-xl font-black tracking-tight text-slate-900">{job ? 'Edit Lowongan' : 'Tambah Lowongan'}</h2></div><button onClick={onClose} disabled={saving} className="grid size-9 place-items-center rounded-xl border border-slate-200 text-slate-500 hover:bg-slate-50"><X className="size-4" /></button></header>
      <form onSubmit={submit} className="no-scrollbar flex-1 overflow-y-auto px-5 py-6 sm:px-7">
        <FormSection title="Informasi dasar" description="Informasi utama yang terlihat pada kartu lowongan.">
          <div className="grid gap-4 sm:grid-cols-2"><TextField label="Judul pekerjaan" required value={values.title} onChange={(value) => set('title', value)} placeholder="Contoh: Barista Part-Time" /><TextField label="Nama perusahaan" required value={values.company_name} onChange={(value) => set('company_name', value)} placeholder="Kopi Nusantara" /><TextField label="Lokasi" required value={values.location} onChange={(value) => set('location', value)} placeholder="Jakarta Selatan" /><TextField label="Kategori" required value={values.category} onChange={(value) => set('category', value)} placeholder="Food & Beverage" /><SelectField label="Tipe kerja" value={values.work_type} options={['Full-Time', 'Part-Time', 'Freelance', 'Temporary', 'Internship']} onChange={(value) => set('work_type', value as WorkType)} /><SelectField label="Mode kerja" value={values.work_mode} options={['On-site', 'Hybrid', 'Remote']} onChange={(value) => set('work_mode', value as WorkMode)} /></div>
          <div className="mt-4"><TextField label="URL logo perusahaan" value={values.company_logo_url || ''} onChange={(value) => set('company_logo_url', value || null)} placeholder="https://..." /></div>
          <label className="mt-3 flex cursor-pointer items-center gap-3 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-3 text-xs font-bold text-slate-600 transition hover:border-brand-300 hover:bg-brand-50"><span className="grid size-9 place-items-center rounded-lg bg-white text-brand-700 shadow-sm">{uploading ? <Loader2 className="size-4 animate-spin" /> : <ImagePlus className="size-4" />}</span><span><span className="block text-slate-800">Atau unggah logo</span><span className="mt-0.5 block font-medium text-slate-400">PNG, JPG, atau WebP · Maks. 2 MB</span></span><Upload className="ml-auto size-4 text-slate-400" /><input type="file" className="hidden" accept="image/png,image/jpeg,image/webp" disabled={uploading} onChange={(event) => void upload(event.target.files?.[0])} /></label>
        </FormSection>
        <FormSection title="Detail pekerjaan" description="Jelaskan peran secara singkat, jelas, dan menarik."><div className="space-y-4"><TextArea label="Deskripsi singkat" required rows={2} maxLength={180} value={values.short_description} onChange={(value) => set('short_description', value)} placeholder="Ringkasan singkat untuk kartu lowongan…" /><TextArea label="Deskripsi lengkap" required rows={5} value={values.description} onChange={(value) => set('description', value)} placeholder="Ceritakan posisi, tim, dan lingkungan kerja…" /><TextArea label="Kualifikasi" required rows={4} hint="Satu poin per baris" value={requirements} onChange={setRequirements} placeholder={'Minimal SMA/SMK\nBersedia bekerja shift'} /><TextArea label="Tanggung jawab" rows={4} hint="Satu poin per baris" value={responsibilities} onChange={setResponsibilities} placeholder={'Melayani pelanggan\nMenjaga kebersihan area kerja'} /><TextArea label="Tentang perusahaan" rows={3} value={values.company_description} onChange={(value) => set('company_description', value)} placeholder="Perkenalkan perusahaan secara singkat…" /></div></FormSection>
        <FormSection title="Kompensasi" description="Nominal boleh dikosongkan bila menggunakan teks tampilan."><div className="grid gap-4 sm:grid-cols-2"><NumberField label="Gaji minimum" value={values.salary_min} onChange={(value) => set('salary_min', value)} placeholder="25000" /><NumberField label="Gaji maksimum" value={values.salary_max} onChange={(value) => set('salary_max', value)} placeholder="40000" /><TextField label="Teks gaji" value={values.salary_display || ''} onChange={(value) => set('salary_display', value || null)} placeholder="Rp25.000 – Rp40.000 / jam" /><TextField label="Periode" value={values.salary_period || ''} onChange={(value) => set('salary_period', value || null)} placeholder="jam" /></div></FormSection>
        <FormSection title="Cara melamar" description="Pelamar akan diarahkan langsung ke kontak perusahaan."><div className="grid gap-4 sm:grid-cols-2"><SelectField label="Metode lamaran" value={values.application_method} options={['whatsapp', 'email', 'url']} optionLabels={['WhatsApp', 'Email', 'Tautan eksternal']} onChange={(value) => set('application_method', value as ApplicationMethod)} />{values.application_method === 'whatsapp' && <TextField label="Nomor WhatsApp" required value={values.application_whatsapp || ''} onChange={(value) => set('application_whatsapp', value || null)} placeholder="6281212345678" />}{values.application_method === 'email' && <TextField label="Email lamaran" type="email" required value={values.application_email || ''} onChange={(value) => set('application_email', value || null)} placeholder="karier@perusahaan.co.id" />}{values.application_method === 'url' && <TextField label="Tautan lamaran" type="url" required value={values.application_url || ''} onChange={(value) => set('application_url', value || null)} placeholder="https://perusahaan.co.id/karier" />}</div></FormSection>
        <FormSection title="Status" description="Atur visibilitas dan penanda khusus lowongan."><div className="grid gap-3 sm:grid-cols-3"><Toggle label="Aktif" description="Tampil di portal publik" checked={values.is_active} onChange={(value) => set('is_active', value)} /><Toggle label="Pilihan" description="Diprioritaskan di daftar" checked={values.is_featured} onChange={(value) => set('is_featured', value)} /><Toggle label="Segera" description="Tampilkan badge urgent" checked={values.is_urgent} onChange={(value) => set('is_urgent', value)} /></div></FormSection>
        <div className="h-20" />
      </form>
      <footer className="absolute inset-x-0 bottom-0 flex items-center justify-end gap-2 border-t border-slate-200 bg-white/95 px-5 py-4 backdrop-blur sm:rounded-b-3xl sm:px-7"><button type="button" onClick={onClose} disabled={saving} className="rounded-xl border border-slate-200 px-5 py-3 text-xs font-extrabold text-slate-600 hover:bg-slate-50">Batal</button><button type="submit" onClick={() => document.querySelector<HTMLFormElement>('[aria-labelledby="job-form-title"] form')?.requestSubmit()} disabled={saving || uploading} className="inline-flex min-w-36 items-center justify-center gap-2 rounded-xl bg-brand-700 px-5 py-3 text-xs font-extrabold text-white hover:bg-brand-800 disabled:opacity-60">{saving && <Loader2 className="size-4 animate-spin" />}{saving ? 'Menyimpan…' : job ? 'Simpan Perubahan' : 'Terbitkan Lowongan'}</button></footer>
    </section></div>
  )
}

function stripJob(job: Job): JobFormValues { const { id: _id, created_at: _created, updated_at: _updated, ...values } = job; return values }
function splitLines(value: string) { return value.split('\n').map((item) => item.trim()).filter(Boolean) }
function FormSection({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <section className="mb-5 rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><h3 className="text-sm font-black text-slate-900">{title}</h3><p className="mt-1 text-xs leading-5 text-slate-400">{description}</p><div className="mt-5">{children}</div></section> }
const fieldClass = 'focus-ring w-full rounded-xl border border-slate-200 bg-white px-3.5 py-3 text-sm font-semibold text-slate-800 outline-none transition placeholder:font-normal placeholder:text-slate-400 focus:border-brand-400'
function TextField({ label, value, onChange, placeholder, required, type = 'text' }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; required?: boolean; type?: string }) { return <label className="block"><span className="mb-1.5 block text-xs font-extrabold text-slate-600">{label}{required && <span className="text-red-500"> *</span>}</span><input className={fieldClass} type={type} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} required={required} /></label> }
function NumberField({ label, value, onChange, placeholder }: { label: string; value: number | null; onChange: (value: number | null) => void; placeholder?: string }) { return <label className="block"><span className="mb-1.5 block text-xs font-extrabold text-slate-600">{label}</span><input className={fieldClass} type="number" min="0" value={value ?? ''} onChange={(event) => onChange(event.target.value ? Number(event.target.value) : null)} placeholder={placeholder} /></label> }
function TextArea({ label, value, onChange, placeholder, required, rows, hint, maxLength }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; required?: boolean; rows: number; hint?: string; maxLength?: number }) { return <label className="block"><span className="mb-1.5 flex justify-between text-xs font-extrabold text-slate-600"><span>{label}{required && <span className="text-red-500"> *</span>}</span>{hint && <span className="font-medium text-slate-400">{hint}</span>}</span><textarea className={`${fieldClass} resize-y leading-6`} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} required={required} rows={rows} maxLength={maxLength} /></label> }
function SelectField({ label, value, options, optionLabels, onChange }: { label: string; value: string; options: string[]; optionLabels?: string[]; onChange: (value: string) => void }) { return <label className="block"><span className="mb-1.5 block text-xs font-extrabold text-slate-600">{label}</span><select className={fieldClass} value={value} onChange={(event) => onChange(event.target.value)}>{options.map((option, index) => <option key={option} value={option}>{optionLabels?.[index] || option}</option>)}</select></label> }
function Toggle({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex cursor-pointer items-center justify-between rounded-xl border border-slate-200 p-3.5"><span><span className="block text-xs font-extrabold text-slate-800">{label}</span><span className="mt-1 block text-[10px] text-slate-400">{description}</span></span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="size-4 accent-brand-700" /></label> }
