import { Eye, EyeOff, FilePenLine, ImagePlus, Plus, RefreshCw, Trash2 } from 'lucide-react'
import type { PosterSlide } from '../../types/posterSlide'

export function PosterSlidesPanel({ slides, loading, error, onCreate, onEdit, onDelete, onToggle, onReload }: { slides: PosterSlide[]; loading: boolean; error: string; onCreate: () => void; onEdit: (slide: PosterSlide) => void; onDelete: (slide: PosterSlide) => void; onToggle: (slide: PosterSlide) => void; onReload: () => void }) {
  return <div className="animate-fade-up"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#71318f]">Instagram poster manager</p><h2 className="mt-2 text-[32px] font-black leading-none tracking-[-.045em] text-[#18181d] sm:text-[42px]">Poster teratas,<br />mudah diperbarui.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-[#77736c]">Kelola gambar portrait, teks, tautan, urutan, dan status setiap slide.</p></div><button onClick={onCreate} className="focus-ring inline-flex items-center justify-center gap-2 rounded-full bg-[#18181d] px-5 py-3.5 text-xs font-extrabold text-white shadow-[0_8px_0_#d3cec4] transition hover:-translate-y-0.5 hover:bg-[#71318f]"><Plus className="size-4" /> Tambah Poster</button></div>
    <section className="mt-8 rounded-[28px] border border-[#d6d1c8] bg-[#faf8f3] p-4 sm:p-6"><div className="mb-5 flex items-center justify-between"><div><p className="text-sm font-black text-[#222127]">Daftar poster</p><p className="mt-1 text-[11px] text-[#8a877f]">Urutan terkecil tampil lebih dulu.</p></div><button onClick={onReload} className="grid size-10 place-items-center rounded-full bg-[#ffcf4a] text-[#18181d]" aria-label="Muat ulang poster"><RefreshCw className={`size-4 ${loading ? 'animate-spin' : ''}`} /></button></div>
      {error ? <div className="rounded-2xl border border-red-100 bg-red-50 p-4 text-xs text-red-700">{error}</div> : loading ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 3 }).map((_, index) => <div key={index} className="h-80 animate-pulse rounded-3xl bg-[#e9e5dd]" />)}</div> : slides.length ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{slides.map((slide) => <PosterAdminCard key={slide.id} slide={slide} onEdit={() => onEdit(slide)} onDelete={() => onDelete(slide)} onToggle={() => onToggle(slide)} />)}</div> : <div className="grid min-h-64 place-items-center rounded-2xl border border-dashed border-[#d6d1c8] text-center"><div><ImagePlus className="mx-auto size-8 text-[#9f9a91]" /><p className="mt-3 text-sm font-black text-[#29282e]">Belum ada poster</p><p className="mt-1 text-xs text-[#8a877f]">Tambahkan poster pertama untuk portal publik.</p></div></div>}
    </section>
  </div>
}

function PosterAdminCard({ slide, onEdit, onDelete, onToggle }: { slide: PosterSlide; onEdit: () => void; onDelete: () => void; onToggle: () => void }) {
  return <article className="overflow-hidden rounded-3xl border border-[#d6d1c8] bg-white"><div className="relative aspect-[4/3] overflow-hidden bg-gradient-to-br from-[#102a63] to-[#963eb1]">{slide.image_url ? <img src={slide.image_url} alt={slide.alt_text} className="size-full object-cover" /> : <div className="absolute inset-0 p-5 text-white"><img src="/careerhub-logo.jpg" alt="" className="size-11 rounded-full" /><p className="absolute inset-x-5 bottom-5 text-lg font-black leading-tight">{slide.title}</p></div>}<span className={`absolute right-3 top-3 rounded-full px-2.5 py-1 text-[9px] font-black uppercase tracking-wider ${slide.is_active ? 'bg-[#dcf5e3] text-[#176b37]' : 'bg-[#ebe7df] text-[#77736c]'}`}>{slide.is_active ? 'Aktif' : 'Jeda'}</span></div><div className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-black text-[#242329]">{slide.title}</p><p className="mt-1 line-clamp-2 text-[11px] leading-5 text-[#8a877f]">{slide.subtitle || 'Tanpa deskripsi'}</p></div><span className="shrink-0 rounded-full bg-[#eee8f1] px-2.5 py-1 text-[9px] font-black text-[#71318f]">#{slide.sort_order}</span></div><div className="mt-4 grid grid-cols-3 gap-2"><button onClick={onEdit} className="inline-flex items-center justify-center gap-1.5 rounded-full bg-[#e9e8ff] py-2.5 text-[10px] font-extrabold text-[#4d54c8]"><FilePenLine className="size-3.5" /> Edit</button><button onClick={onToggle} className="inline-flex items-center justify-center gap-1.5 rounded-full bg-[#ebe7df] py-2.5 text-[10px] font-extrabold text-[#555159]">{slide.is_active ? <EyeOff className="size-3.5" /> : <Eye className="size-3.5" />}{slide.is_active ? 'Jeda' : 'Aktif'}</button><button onClick={onDelete} className="inline-flex items-center justify-center gap-1.5 rounded-full bg-[#ffe3df] py-2.5 text-[10px] font-extrabold text-[#bf473b]"><Trash2 className="size-3.5" /> Hapus</button></div></div></article>
}
