import { ArrowLeft, ArrowRight, BriefcaseBusiness, CalendarCheck2, CircleDollarSign, Clock3, HeartHandshake, ShieldCheck, TrendingUp, UsersRound } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Brand } from '../components/ui/Brand'

export function FullTimeGuide() {
  return <div className="min-h-screen bg-[#f6f4ef] text-[#19191f] dark:bg-[#0a1020] dark:text-white">
    <header className="sticky top-0 z-30 border-b border-[#dedad2] bg-[#f6f4ef]/90 backdrop-blur-xl dark:border-white/10 dark:bg-[#0a1020]/90"><div className="mx-auto flex h-[72px] max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8"><Brand /><Link to="/" className="focus-ring inline-flex items-center gap-2 rounded-full border border-[#d6d1c8] bg-white px-4 py-2.5 text-xs font-extrabold text-[#4f4c53] transition hover:-translate-x-0.5 hover:border-[#71318f] hover:text-[#71318f] dark:border-white/15 dark:bg-white/5 dark:text-white"><ArrowLeft className="size-4" /> Kembali</Link></div></header>

    <main>
      <section className="relative overflow-hidden border-b border-[#dedad2] dark:border-white/10"><div className="pointer-events-none absolute -right-28 -top-32 size-[520px] rounded-full border-[82px] border-[#71318f]/12" /><div className="pointer-events-none absolute -bottom-56 -left-20 size-[440px] rounded-full bg-[#ffcf4a]/35 blur-2xl" /><div className="relative mx-auto grid max-w-7xl gap-12 px-4 py-16 sm:px-6 sm:py-24 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:px-8 lg:py-28">
        <div><span className="inline-flex items-center gap-2 rounded-full bg-[#71318f] px-3.5 py-2 text-[10px] font-black uppercase tracking-[.14em] text-white"><BriefcaseBusiness className="size-4" /> Panduan kategori kerja</span><h1 className="mt-7 max-w-3xl text-[46px] font-black leading-[.98] tracking-[-.06em] sm:text-[68px]">Mengenal kerja<br /><span className="text-[#71318f] dark:text-[#d08be9]">Full-Time.</span></h1><p className="mt-6 max-w-2xl text-base leading-8 text-[#6f6b72] dark:text-slate-300">Pekerjaan Full-Time adalah peran dengan jam kerja utama dan tanggung jawab berkelanjutan di sebuah perusahaan. Cocok untuk kamu yang mencari stabilitas, pertumbuhan karier, dan keterlibatan lebih dalam bersama tim.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/?workType=Full-Time#lowongan" className="focus-ring inline-flex items-center justify-center gap-2 rounded-full bg-[#18181d] px-6 py-3.5 text-sm font-extrabold text-white shadow-[0_8px_0_#d3cec4] transition hover:-translate-y-1 hover:bg-[#71318f]">Lihat Lowongan Full-Time <ArrowRight className="size-4" /></Link><a href="#pelajari" className="focus-ring inline-flex items-center justify-center rounded-full border-2 border-[#18181d] px-6 py-3.5 text-sm font-extrabold transition hover:bg-white dark:border-white/30 dark:hover:bg-white/10">Pelajari dahulu</a></div></div>
        <div className="relative mx-auto w-full max-w-md"><div className="relative overflow-hidden rounded-[36px] bg-[#18181d] p-7 text-white shadow-[0_34px_90px_rgba(24,24,29,.22)] sm:p-9"><div className="absolute -right-16 -top-16 size-56 rounded-full border-[38px] border-[#5962f4]/70" /><div className="absolute -bottom-28 -left-20 size-60 rounded-full bg-[#ffcf4a]" /><div className="relative"><p className="text-[10px] font-black uppercase tracking-[.18em] text-white/35">Gambaran singkat</p><h2 className="mt-3 text-3xl font-black tracking-[-.045em]">Komitmen penuh,<br />ruang tumbuh lebih luas.</h2><div className="mt-10 grid gap-3 sm:grid-cols-2"><Metric icon={<Clock3 />} value="±40 jam" label="per minggu" /><Metric icon={<CalendarCheck2 />} value="Terjadwal" label="ritme konsisten" /><Metric icon={<UsersRound />} value="Satu tim" label="kolaborasi rutin" /><Metric icon={<TrendingUp />} value="Berjenjang" label="jalur karier" /></div></div></div></div>
      </div></section>

      <section id="pelajari" className="mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-24 lg:px-8"><div className="max-w-2xl"><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#71318f] dark:text-[#d08be9]">Apa yang biasanya didapat?</p><h2 className="mt-3 text-3xl font-black tracking-[-.045em] sm:text-4xl">Lebih dari sekadar jam kerja.</h2><p className="mt-4 text-sm leading-7 text-[#77736c] dark:text-slate-400">Setiap perusahaan memiliki kebijakan berbeda, tetapi posisi Full-Time umumnya menawarkan struktur dan dukungan yang lebih konsisten.</p></div><div className="mt-9 grid gap-4 md:grid-cols-3"><Benefit icon={<CircleDollarSign />} title="Penghasilan stabil" text="Kompensasi rutin dengan detail periode dan komponen yang disepakati sejak awal." /><Benefit icon={<ShieldCheck />} title="Perlindungan kerja" text="Kontrak, hak cuti, jaminan sosial, dan kebijakan perusahaan yang lebih terstruktur." /><Benefit icon={<TrendingUp />} title="Pertumbuhan karier" text="Target, evaluasi, pelatihan, dan peluang promosi dalam perjalanan jangka panjang." /></div></section>

      <section className="border-y border-[#dedad2] bg-white dark:border-white/10 dark:bg-[#10182a]"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-16 sm:px-6 sm:py-24 lg:grid-cols-2 lg:px-8"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#71318f] dark:text-[#d08be9]">Sebelum melamar</p><h2 className="mt-3 text-3xl font-black tracking-[-.045em]">Periksa hal-hal penting ini.</h2><p className="mt-4 max-w-lg text-sm leading-7 text-[#77736c] dark:text-slate-400">Lowongan yang baik menjelaskan ekspektasi dengan jujur. Jangan ragu bertanya sebelum menyetujui penawaran.</p></div><div className="grid gap-3">{['Jam dan hari kerja, termasuk kebijakan lembur.', 'Status kontrak, masa percobaan, serta periode evaluasi.', 'Gaji, tunjangan, cuti, BPJS, dan manfaat lainnya.', 'Lokasi kerja serta kebijakan on-site, hybrid, atau remote.', 'Ruang lingkup pekerjaan dan indikator keberhasilan.'].map((item, index) => <div key={item} className="flex items-start gap-4 rounded-2xl border border-[#dedad2] bg-[#faf8f3] p-4 dark:border-white/10 dark:bg-white/[.04]"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-[#ffcf4a] text-xs font-black text-[#29251b]">{index + 1}</span><p className="pt-1 text-sm font-bold leading-6 text-[#504d54] dark:text-slate-200">{item}</p></div>)}</div></div></section>

      <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-24 lg:px-8"><div className="relative overflow-hidden rounded-[34px] bg-gradient-to-br from-[#4d54d8] to-[#8c37a9] px-6 py-12 text-white sm:px-10 sm:py-14 lg:flex lg:items-center lg:justify-between lg:gap-12"><div className="absolute -right-16 -top-20 size-64 rounded-full border-[42px] border-white/10" /><div className="relative max-w-2xl"><span className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[.16em] text-white/55"><HeartHandshake className="size-4" /> Langkah berikutnya</span><h2 className="mt-3 text-3xl font-black tracking-[-.045em] sm:text-4xl">Siap mencari peran jangka panjang?</h2><p className="mt-4 text-sm leading-7 text-white/70">Bandingkan tanggung jawab, budaya kerja, kompensasi, dan peluang berkembang sebelum menentukan pilihan.</p></div><Link to="/?workType=Full-Time#lowongan" className="focus-ring relative mt-7 inline-flex shrink-0 items-center gap-2 rounded-full bg-white px-6 py-3.5 text-sm font-extrabold text-[#4d2b70] shadow-xl transition hover:-translate-y-1 lg:mt-0">Jelajahi Full-Time <ArrowRight className="size-4" /></Link></div></section>
    </main>

    <footer className="border-t border-white/10 bg-[#080f20] px-4 py-8 text-center text-xs text-slate-400">© {new Date().getFullYear()} Careerhub.indonesia · Panduan kerja Full-Time</footer>
  </div>
}

function Metric({ icon, value, label }: { icon: React.ReactNode; value: string; label: string }) { return <div className="rounded-2xl border border-white/10 bg-white/[.07] p-4"><span className="text-[#ffcf4a] [&>svg]:size-5">{icon}</span><p className="mt-4 text-xl font-black">{value}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-wider text-white/40">{label}</p></div> }
function Benefit({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <article className="rounded-[26px] border border-[#dedad2] bg-white p-6 transition duration-300 hover:-translate-y-1 hover:border-[#b268ca] hover:shadow-[0_20px_45px_rgba(40,30,50,.08)] dark:border-white/10 dark:bg-white/[.04]"><span className="grid size-12 place-items-center rounded-2xl bg-[#efe7f3] text-[#71318f] dark:bg-[#d08be9]/10 dark:text-[#d08be9] [&>svg]:size-5">{icon}</span><h3 className="mt-6 text-lg font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-[#77736c] dark:text-slate-400">{text}</p></article> }
